PR book repository
wolox-training/mt-java pull request #4
Opened 2020-12-16 18:08 UTC by torsello

## Summary
- Book repository created
- 'Find Book By Author' Method created

## Feature screenshot
- https://i.imgur.com/szgwdD7.png

## Trello Card
- https://trello.com/c/7gxdOJVp

2020-12-17 17:25 UTC, zeminlu requested changes
Check my comment!

2020-12-17 17:25 UTC, zeminlu commented on src/main/java/com/wolox/training/repositories/BookRepository.java
> +    public Book findByAuthor(String author);
This should return an Optional\<Book\>

2020-12-18 13:11 UTC, julianvasquez-wolox approved these changes

2020-12-18 20:21 UTC, zeminlu approved these changes
LGTM!

2020-12-21 13:32 UTC, merged