PR Book CRUD
wolox-training/mt-java pull request #5
Opened 2020-12-17 13:52 UTC by torsello

## Summary
- Lombok dependency
- Book Service CRUD
- Book Controler CRUD + MediaType differentiation
- Modifying BookController RequestMapping

## Feature screenshot
https://i.imgur.com/CjDtIle.png

## Trello Card
https://trello.com/c/mQQ6KBh7

2020-12-17 19:04 UTC, zeminlu requested changes
Looks good, check my comments!

2020-12-17 19:04 UTC, zeminlu commented on src/main/java/com/wolox/training/dtos/BookDto.java
> +public class BookDto {
Name this one BookDTO

2020-12-17 19:04 UTC, zeminlu commented on src/main/java/com/wolox/training/services/BookService.java
> +        Book book;
Declare and assign on the same line.

2020-12-17 19:04 UTC, zeminlu commented on src/main/java/com/wolox/training/controllers/BookController.java
> +@Controller
Change to @RestController and remove the greeting endpoint and html, given that was just for the first card.

2020-12-17 19:04 UTC, zeminlu commented on build.gradle
> +	compile('org.springframework.boot:spring-boot-starter-thymeleaf')
Given you added Lombok, check out the Lombok card that's at the end of the training so you can start better understanding it's use.

2020-12-18 19:35 UTC, julianvasquez-wolox approved these changes

2020-12-18 19:35 UTC, julianvasquez-wolox commented on src/main/java/com/wolox/training/exceptions/handler/TrainingApplicationExceptionHandler.java
> +        return new GenericError("001", message);
You can use ENUMS for the errors (like codes and description) :)

2020-12-18 19:35 UTC, julianvasquez-wolox commented on src/main/java/com/wolox/training/services/BookService.java
> +        return bookRepository.findById(id).orElseThrow(() -> new ObjectNotFoundException("Book"));
This "Book" string could be a constant

2020-12-18 19:35 UTC, julianvasquez-wolox commented on src/main/java/com/wolox/training/exceptions/handler/TrainingApplicationExceptionHandler.java
> +        return new GenericError("001", message);
@torsello

2020-12-18 20:46 UTC, zeminlu requested changes
Looking good! Check my comments, I think it'll be even clearer with those!

2020-12-18 20:46 UTC, zeminlu commented on src/main/java/com/wolox/training/controllers/BookController.java
> +        Optional<Book> bookOptional = bookService.findByAuthor(bookAuthor);
You could simply do an .orElseThrow to the findByAuthor(bookAuthor) directly in the BookService, just as you do in other cases. And then just return the entity with the book here. It'll let you remove the if/else overhead.

2020-12-18 20:46 UTC, zeminlu commented on src/main/java/com/wolox/training/controllers/BookController.java
> +    @GetMapping("/book/{bookAuthor}")
This is not very RESTful, to be honest. At most you could change the word book for "author", but it's not really the best way to filter by attributes.
But don't worry, you actually don't need to add this endpoint for this Card, only the other ones you did.
Later in the training you'll do this filtering with query parameters.
For the sake of this card (And given you already did some work on it), just change `book` for `author` and that's it.

2020-12-18 20:46 UTC, zeminlu commented on src/main/java/com/wolox/training/services/BookService.java
> +        return bookRepository.findByAuthor(bookAuthor);
You could add the .orElseThrow here :)
It will clear up the logic you added to the controller.

2020-12-21 14:35 UTC, zeminlu approved these changes

2020-12-21 14:37 UTC, merged