PR Feature/user model
wolox-training/mt-java pull request #7
Opened 2020-12-21 14:53 UTC by torsello

## Summary
- User model created

## Feature Screenshot
- https://i.imgur.com/jeLPzyo.png

## Trello Card
- https://trello.com/c/l0zgJfhq

2020-12-21 20:01 UTC, zeminlu requested changes
Looking good! Check my comments.

2020-12-21 20:01 UTC, zeminlu commented on src/main/java/com/wolox/training/models/Book.java
> +    @ManyToMany(cascade = CascadeType.ALL)
Here you don't want to use CascadeType.ALL. That one means (Persist+Delete+Merge+Update+Detach).
Given the users "live/die" independant of the books they may have associated, the only thing you really want here is to keep the Join Table updated. Persist and Delete to a Book would forward the persist/delete operation applied to it's associated Users. Detach is used to manually detach the items from the persistance context (we never do this manually).
So we're left with Merge and Update. Merge persists memory changes to the database, and refresh brings them from the database to memory. These are the only 2 we need here :)

2020-12-21 20:01 UTC, zeminlu commented on src/main/java/com/wolox/training/models/Book.java
> +    @JoinTable(name = "books_users",
Unless you specifically want to rename join table columns or table name, you can skip defining the @JoinTable annotation given everything will be sorted out automatically because of the @ManyToMany relationship.

2020-12-21 20:02 UTC, zeminlu commented on src/main/java/com/wolox/training/models/Users.java
> +public class Users {
Change to "User". And override table name with @Table annotation (you can't use 'user' given it's reserved)

2020-12-21 20:18 UTC, zeminlu approved these changes

2020-12-22 13:14 UTC, julianvasquez-wolox approved these changes

2020-12-22 14:29 UTC, merged